
theme: jekyll-theme-time-machine
title: Defense White Papers in the Asia Pacific
description: Security persepctives and strategies of US allies in the Asia Pacific 2000 - 2017
menu: [
{'name': 'The Project', 'pagename': 'index'},
{'name': 'The SCS Conflict', 'pagename': 'thescsconflict'},
{'name': 'Material', 'pagename': 'material'},
{'name': 'Methodology', 'pagename': 'methodology'},
{'name': 'Temporal Evolution', 'pagename': 'temporalevolution'},
{'name': 'Cross-regional NM', 'pagename': 'crossregionalnetworks'},
{'name': 'Cross-temporal NM', 'pagename': 'crosstemporalnetworks'},
{'name': 'Challenges', 'pagename': 'challenges'},
]
