
theme: jekyll-theme-time-machine
title: Defense White Papers in the Asia Pacific
description: A look at the security persepctives and strategies of U.S. allies in the Asia Pacific over time
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'this a the 2nd page', 'pagename': 'page1'},
{'name': 'Go there', 'pagename': 'page2'},
{'name': 'Yet Another page', 'pagename': 'page3'},
]
