
theme: jekyll-theme-time-machine
title: Defense White Papers in the Asia Pacific
description: A look at the security persepctives and strategies of US allies in the Asia Pacific over time
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'Material', 'pagename': 'material'},
{'name': 'Methodology', 'pagename': 'methodology'},
{'name': 'Challenges', 'pagename': 'challenges'},
{'name': 'Findings', 'pagename': 'findings'},
]
